# This is a basic workflow to help you get started with Actions

name: CI - Pylinter Program

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "python-lint"
  python-lint:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    name: CI workflow
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Checkout repo source code
      uses: actions/checkout@v2
    
    - name: pylinter
      uses: alexanderdamiani/pylinter@v1.3.0
      with:
        python-root: '.'
        flake8-flags: '--count --show-source --statistics --ignore=E501,E401 ./'
        mypy-flags: '--ignore-missing-imports'
        fail-on-isort: false
        
    - name: commit isort changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "Github Action"
        git add -A && git diff-index --cached --quiet HEAD || git commit -m 'isort changes'
    
    - name: push isort changes
      uses: ad-m/github-push-action@v0.5.0
      with:
        github_token: ${{ secrets.ISORT_ACCESS_TOKEN }}
        branch: ${{ github.ref }}
