name: CI - Integration Test 

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
        mongodb-version: [4.0.1]
        python-version: [3.9]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Git checkout 
      uses: actions/checkout@v2

    # Setting up Node.js
    - name: Install Node JS ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    # Setting Up Python
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    # Setting up Python Dependencies    
    - name: Install Python dependencies
      run: |
        sudo apt-get install gcc python-dev libkrb5-dev
        python -m pip install --upgrade pip
        pip install pywinrm[kerberos]
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    # Setting up Newman Dependency
    - name: Install Newman dependency
      run: npm install --prefix tests/postman/

    # Running the API
    - name: Run the API and Postman's tests
      run: |
        python main.py &
        sleep 2
        ./node_modules/newman/bin/newman.js run api-tests.json
        kill -9 `lsof -i:8000 -t`
        
